### ISSUE TITLE
String and Bytes are no longer compatible since OCaml 4.06.0

### ISSUE THREAD

**Issue by AlwaysPS** [zkincaid/srk#1]
Since OCaml 4.06.0, Bytes and String are no longer equivalent by default. That causes trouble when compiling srk with OCaml version newer than (and including) 4.06.0.

To be more specific, errors occur when compiling "src/log.ml" and some other files. It seems "string" is required in these places, but it was supplied with "bytes".

**Comment by zkincaid** [comment]
Thanks for the report.  I pulled in the last few months changes -- the issue should be fixed now.
